### ISSUE TITLE
killall Finder ---->this command wouldn't be executed

### ISSUE THREAD

**Issue by Elinu** [wzxjohn/File-Hidden-Switch-Workflow#1]
hi there ！
hide off this command didn't work well for me，I think there is something wrong with **killall Finder**

**Comment by wzxjohn** [comment]
Can you please tell me your Alfred version and Mac OS X version? Thank you very much!

**Comment by wzxjohn** [comment]
@Elinu Can you please try the new version I have just upload? Maybe this version can solve your problem.

**Comment by Elinu** [comment]
Unfortunately ! I try it again, but the problem persists.

>  Alfred v3.1.1, macOS 10.12
> debug for it show this message
> `[ERROR: action.script] zsh:3: = not found` 
> I use the zsh and already change to zsh from bash

**Comment by Elinu** [comment]
I‘m sorry. Now I use **command+shift+.** to hide and reveal the files , I have just updated the macOS to 10.12, Thank you all the same
